version: '3'
services:
  redis-server:
    image: 'redis'
  node-app:
    build: 
      context: ./globoappserver
    ports:
      - "8080:8080"     
    container_name: api-server  
  ui:
    build:
      context: ./globoapp
    ports:
      - "3000:3000"
    stdin_open: true 
    volumes:
      - ./globoapp:/usr/app